spring:
  application:
    name: deposit-banking-test
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  liquibase:
    enabled: false

logging:
  level:
    root: INFO
    com.banking.deposit: DEBUG

